exclude: "!.md"
fail_fast: true
default_stages: [commit, push]
repos:
  - repo: https://github.com/oxsecurity/megalinter
    rev: v8.0.0 # Git tag specifying the hook, not mega-linter-runner, version
    hooks:
      - id: megalinter-incremental # Faster, less thorough
        stages:
          - commit
        args:
          - mega-linter-runner
          - --containername=megalinter-incremental
          - --flavor=documentation
          - --remove-container
          - --fix
# npx mega-linter-runner -e 'ENABLE=MARKDOWN,YAML' -e 'SHOW_ELAPSED_TIME=true' -e "'APPLY_FIXES=all'" -e "'CLEAR_REPORT_FOLDER=true'" -e "'LOG_LEVEL=warning'" --containername megalinter-incremental --remove-container --fix --filesonly
