---
on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Trigger"]
    types:
      - completed
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    name: "JolieDoc Build"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: fmontesi
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./docker/all.Dockerfile
          push: true
          no-cache: true
          tags: jolielang/docs:latest
